name: thuongoc
description: "A application for checkout and payment"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  app_links: ^7.0.0
  cached_network_image: ^3.4.1
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  forui: ^0.17.0
  forui_assets: ^0.17.1
  get: ^4.7.3
  get_storage: ^2.1.1
  http: ^1.6.0
  intl: ^0.20.2
  pull_to_refresh: ^2.0.0
  qr_code_scanner_plus: ^2.0.14
  sunmi_flutter_plugin_printer: ^1.0.7+7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
